# Generated by Django 2.1.5 on 2020-02-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20200219_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to=''),
        ),
    ]
