# Generated by Django 2.1.5 on 2020-02-20 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0007_auto_20200219_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wishlist.Item')),
            ],
        ),
    ]
