# Generated by Django 2.1.5 on 2020-02-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0010_auto_20200220_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='boughtby',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
