# Generated by Django 2.1.5 on 2020-02-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_auto_20200219_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
